#build-stage
FROM node:22-alpine as builder

WORKDIR /app

RUN corepack enable

COPY . .

RUN pnpm --filter app-integration-service install --frozen-lockfile
RUN pnpm turbo run build --filter=app-integration-service

#production-stage
FROM node:22-alpine as production


WORKDIR /app

COPY --from=builder /app/services/app-integration-service ./services/app-integration-service
COPY --from=builder /app/packages ./packages
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/package.json ./

WORKDIR /app/services/app-integration-service

EXPOSE 5001
CMD ["node", "dist/index.js"]