# Builder stage
FROM node:22-alpine as builder

WORKDIR /app

RUN corepack enable

COPY . .

RUN pnpm --filter api-gateway install --frozen-lockfile
RUN pnpm turbo run build --filter=api-gateway


FROM node:22-alpine as production

ENV NODE_ENV=production

WORKDIR /app

COPY --from=builder /app/services/api-gateway ./services/api-gateway
COPY --from=builder /app/packages ./packages
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/package.json ./

WORKDIR /app/services/api-gateway

EXPOSE 5003

CMD ["node", "dist/index.js"]