#build-stage
FROM node:22-alpine as builder

WORKDIR /app

RUN corepack enable

COPY . .

RUN pnpm --filter secure-bot install --frozen-lockfile
RUN pnpm --filter secure-bot exec prisma generate
RUN pnpm turbo run build --filter=secure-bot

#production-stage
FROM node:22-alpine as prodcution

# Install Git to support repository cloning during security scans
RUN apk add --no-cache git

WORKDIR /app

COPY --from=builder /app/services/secure-bot ./services/secure-bot
COPY --from=builder /app/packages ./packages
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/package.json ./

EXPOSE 5002

WORKDIR /app/services/secure-bot

CMD ["node","dist/index.js"]