#build stage
FROM node:22-alpine as builder

WORKDIR /app

RUN corepack enable

COPY . .
RUN pnpm --filter auth-service install --frozen-lockfile
RUN pnpm --filter auth-service exec prisma generate
RUN pnpm turbo run build --filter=auth-service


#Production stage
FROM node:22-alpine as production

WORKDIR /app

COPY --from=builder /app/services/auth-service ./services/auth-service
COPY --from=builder /app/packages ./packages
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/package.json ./

WORKDIR /app/services/auth-service

EXPOSE 5000

CMD ["node","dist/index.js"]