name: deploy by updating ansible playbook

on:
  workflow_dispatch:
  workflow_call:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Ansible
        run: |
          sudo apt update
          sudo apt install ansible -y

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          cat << 'EOF' | tr -d '\r' > ~/.ssh/id_rsa
          ${{ secrets.SSH_PRIVATE_KEY }}
          EOF
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts

      - name: Create env files
        run: |
          echo "${{ secrets.DOTENV }}" > .env
          mkdir -p services/api-gateway services/auth-service services/app-integration-service services/secure-bot
          cat << 'EOF' > services/api-gateway/.env.prod
          ${{ secrets.API_GATEWAY_ENV }}
          EOF
          cat << 'EOF' > services/auth-service/.env.prod
          ${{ secrets.AUTH_SERVICE_ENV }}
          EOF
          cat << 'EOF' > services/app-integration-service/.env.prod
          ${{ secrets.APP_INTEGRATION_ENV }}
          EOF
          cat << 'EOF' > services/secure-bot/.env.prod
          ${{ secrets.SECURE_BOT_ENV }}
          EOF

      - name: Run Ansible playbook
        run: |
          ansible-playbook -i ansible/inventory ansible/site.yml \
          --extra-vars "domain_name=${{ secrets.DOMAIN_NAME }} certbot_email=${{ secrets.CERTBOT_EMAIL }}"